base_url = "https://imdanieldev.github.io/blog"
compile_sass = true
theme = "mytheme"
title = "وبلاگ دانیال"
description = "این وبلاگ برای من است."
build_search_index = true
[markdown]
highlight_code = true

[extra]
